### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by O13SC3N3** [BlackJar72/DoomlikeDungeons#22] opened 2019-02-06 01:19 UTC
I am pretty sure this may be a conflicting mod, but been searching for hours so here is the crash log which is blaming DLD

https://paste.dimdev.org/itezibihut.mccrash

**Comment by BlackJar72** [comment] 2019-02-06 01:45
Could you please post your nbt.cfg -- it think its config problem them.  That file is notoriously easy to mess-up; one reason there isn't more special loot by default is last time I tried I created crashes.

Also, if you aren't using the latest official version then the JSON nbt type will not exist and will crash.  And it looks like that might have happened: `No enum constant jaredbgreat.dldungeons.nbt.NBTType.JSON`

**Comment by O13SC3N3** [comment] 2019-02-06 02:28
`#Each line is has the following components:
#label type name data
#
#label is what you use to add it to an itam or combine it with othe tags (must be unique)
#type is the NBT data type -- and valid type but list can be used
#name is the name of the data field in the NBT file
#data is what it holds
#
#I'm not giving a full NBT course here -- I'm just learning that myself, but below are some examples.
#More info can be found online in places such as the Minecraft Wiki
#This is a good start: http://minecraft.gamepedia.com/Player.dat_format#Item_structure
#
#Whether or not this might latter be applicable to blocks or mobs has not been decided; 
#For now NBT can only be used for loot items.
#
#In addition to normal NBT tags there is an Ench tag as a convenience for enchanting...
#    label ench id lvl
#...and a Group options that simply allows several additions to be put into on label.
#
#WARNING: This can be easy to mess-up, and there is no error checking (but the game may crash on start-up)
#
#For defining entire NBT tags in one go, the json "type" can be used. To define a tag, copy the output of a command
#like "/blockdata <x> <y> <z> {}", pointed at a chest containing desired items, then put the NBT tag of the item you want to copy.
#Do not define a name for this type.
#If you have CraftTweaker, holding the item with wanted data and doing "/ct nbt" 
#will output a clickable link to copy the NBT data to paste in here.


#Basic Potions
HEALTH1 Json {Potion: "minecraft:healing"}
HEALTH2 Json {Potion: "minecraft:strong_healing"}
REGEN1  Json {Potion: "minecraft:regeneration"}
REGEN2  Json {Potion: "minecraft:strong_regeneration"}
REGENX  Json {Potion: "minecraft:long_regeneration"}

#Hard way to make a custom enchant
SHARP Short id 16
LOOT  Short id 21
SILK  Short id 33
LVL1  Short lvl 1
LVL3  Short lvl 3
SLICE String Name "Clean Slicer"
SLNM  Compound display SLICE

SHARP3 Compound 0 SHARP,LVL3
LOOT1  Compound 1 LOOT,LVL1
SILK1  Compound 2 SILK,LVL1
SLEN   List     ench SHARP3,LOOT1,SILK1
SLSW   Group    Slice SLEN,SLNM

#Easy way to make a custom enchant
ETERNAL Byte Unbreakable 1
EEGG1   Ench 35 3
EEGG3   Ench 32 5
EEGG5   String   Name "Fortuna Major"
EEGG6   Compound display EEGG5
VANILLAWORLD Group EasterEgg EEGG1,EEGG3,EEGG6,ETERNAL`

**Comment by O13SC3N3** [comment] 2019-02-06 02:31
I havent tried doing anything with the configs yet if that helps. Im getting the same issue with the last 3 versions. Even deleted configs each isntall, why I think its another mod something with OpenAL in the console saying only one can be at a time or something or other.

**Comment by BlackJar72** [comment] 2019-02-06 09:30
Well, it looks like the problem is that Gradle, Forge's build scripts, and / or Java decided to suck -- functions and constants that are in the code and work when run from eclipse somehow aren't when compiled and used in the game normally.  I put in a hack to get around the magically disappearing code.

Really, this is why its probably about time to move on -- when I played the game frequently and enthusiastically I always used the latest version of my own mods and always found problems like this quickly without formal testing.  Now I'm lazy about testing and don't see problems like this myself -- if it worked in eclipse I'm likely to say, "OK, works," and move-on without updating a world where I do much or where it won't change anything.

**Comment by BlackJar72** [comment] 2019-02-06 09:31
I just uploaded a hack to work around this problem if you want to try it -- version 1.12.3.

**Comment by O13SC3N3** [comment] 2019-02-06 16:22
Loads up and seems to be working correctly so far... Ill let you know if anything changes. Thanks again!

**Comment by BlackJar72** [comment] 2019-02-07 19:52
If things are still going good I think I'll just close this.

**Closed as completed by BlackJar72** 2019-02-07 19:52 UTC
