### ISSUE TITLE
Mass amount of Wither Skeletons in nether dungeons

### ISSUE THREAD

**Issue by Kowagatte** [BlackJar72/DoomlikeDungeons#16] opened 2018-11-26 07:21 UTC
When exploring dungeons in the nether I always encounter a glitched wither skeleton spawner that spawns so many wither skeletons it crashes my server. I assume its because in the dungeon schematics one of the spawner's has no spawn delay. In the configuration files for the nether dungeons I turned off the wither skeleton spawn and I still encounter the problem after re-generating the nether and the dungeons.

**Comment by BlackJar72** [comment] 2018-11-26 21:34
This is an old problem, its caused by an interaction with a certain other mod.  All the spawners this mod places are vanilla.  Someone found which mod it was -- EnderIO maybe (are you using that?), but I can't remember for sure.  The best idea I can come up with, assuming you want to keep all the mods, is to edit the nether.cfg to remove all skeleton varieties; maybe replace them with modded mobs.

**Comment by Kowagatte** [comment] 2018-11-28 10:34
I don't have enderIO on this server, I can try to remove all the skeleton varieties. I already removed the wither skeleton from the nether config but the issue still persists.

**Comment by BlackJar72** [comment] 2018-11-28 22:26
Well, I'm not sure what to say -- remove all skeleton spawned?  Set it to not generate in the nether?

Since the spawners themselves are just the vanilla block using the vanilla logic I'm not sure I can fix them.  :(

**Comment by Kowagatte** [comment] 2018-11-30 08:24
I found multiple spawners that work. From what I have noticed the wither skeleton spawners are the ones working perfectly fine. It's actually the skeleton spawners that are bugged. This is the result of standing next to the spawner for more than 3 seconds (Not Hyperbole, this happens so fast after 20 seconds the server is overloaded and crashes.)
![Mass Spawning](https://imgur.com/ytL54me.png)
Its a spawner that looks like this that is causing the issue.
![Spawner](https://imgur.com/l7mr7e8.png)
On inspection of the NBT of the skeleton spawners wither skeletons are not even a listed entity in the spawn potentials. and there is no invalid NBT data on the broken spawner. This being a working spawners NBT
![NBT](https://imgur.com/a9dDjF8.png)
and this one being a broken spawners NBT
![NBT2](https://imgur.com/BQubFgs.png)
A side note is the delay is 0s but that is just initial spawning delay and makes no difference. I found a broken one with a longer delay as well.
The amount of nearby wither skeletons should not exceed 6 according to the NBT data of the spawner as well. Not only this but zero normal skeletons spawn from the bugged spawners.
Spawning in a mob spawner placing it in the nether and right clicking it with a skeleton egg yeilds this nbt
![NBT3](https://imgur.com/sY0cfG2.png)
this spawner works perfectly fine in the nether it spawns wither skeletons, normal skeletons and does not spawn a mass amount of skeletons. It's nbt is also the same as the spawners generated from your dungeons.

After testing and reading code. I tried on a fresh install and it's not doomlike dungeons causing the modified spawning. I am unsure of what mod conflicts with DLD to cause this error though. So, I give up and am just going to remove nether dungeons.

**Comment by BlackJar72** [comment] 2018-11-30 21:55
I'm sorry to hear that and that I can't really fix it on my end.  This would not be the first time a mod has broken skeleton spawners in the nether -- maybe related to code for some of the odd vanilla rules?  I should probably changes the themes not to have skeleton spawners in nether dungeons, just to be safe for everyone.  Thanks for many me aware of this.

**Comment by BlackJar72** [comment] 2019-01-16 03:59
This mod doesn't actually change spawner behavior, it only causes skeleton spawners to exist in the nether.  The something in the Minecraft code makes these fragile, and something else is causing them to then malfunction.  As this mod doesn't actually cause them to the spawners to malfunction I'm calling this invalid and closing the issue; there is nothing I can do on my end to fix it, other perhaps remove them entirely from the default nether theme.

**Closed as completed by BlackJar72** 2019-01-16 03:59 UTC
Labels: invalid
