### ISSUE TITLE
[1.7.10] empty chest generation

### ISSUE THREAD

**Issue by Fabboz** [BlackJar72/DoomlikeDungeons#15] opened 2018-09-09 15:15 UTC
Every time a dungeon spawn a large amount of empty chest are generated in empty chunks near spawn point (try deleting all the blocks of the spawn area with mc edit).
Don't seem to happen in area loaded with a chunk loaded and not empty.
The amount of chest increase at every dungeon spawn (can see with mc edit).

**Comment by BlackJar72** [comment] 2018-09-09 19:50
I don't have mc edit, but I may look into this when I can.  The importance does seem limit though due to the age of the version and the strange circumstances required to produce it.

**Comment by Fabboz** [comment] 2018-09-11 07:27
the chests spawn even if i fill the portion of map completely with bedrock.

**Comment by BlackJar72** [comment] 2018-09-11 10:00
OK, I'll download an x-ray mod and see if I can duplicate this -- though I can't imagine what could possibly cause something like that.

**Comment by BlackJar72** [comment] 2018-09-11 10:27
OK, confirmed.  It isn't exactly near spawn, its near 0,0 -- specifically between 0,0 and 128, 128.  I don't have time to deal with this right now, but I'll look into it when I can.  Perhaps duplicating chest placements in that location?

**Comment by Fabboz** [comment] 2018-09-11 13:12
> Perhaps duplicating chest placements in that location?

Yes, exactly.

**Comment by BlackJar72** [comment] 2018-09-11 20:48
OK, it seems some code from newer versions was accidentally copied back to 1.7.10 at some point (perhaps by git?) -- this chest placement to be run twice, though once without the proper variable setting to make it work (so the were placed relative to the origin of the world map rather than the dungeon map).

It should be fixed now -- just waiting for Curse to approve the file.

**Closed as completed** 2018-09-11 21:28 UTC
Labels: bug
